#! /bin/bash

__prompt(){
    local __CWD="\[\033[37m\]\w\[\033[00m\]"
    export PS1="${__CWD}\$ "
    export LS_COLORS=$LS_COLORS:'di=0;94:' 
}

__export() {
    export EDITOR=vim
    export BROWSER=firefox
}

__alias() {
    alias ascii="figlet -f bigmoney-ne"
    alias shutdown="shutdown -h now"
    alias restart="xrdb $HOME/.Xresources"
    alias pt="setxkbmap -model abnt2 -layout br -variant abnt2"
    alias en="setxkbmap -layout us -variant intl"
}

__func() {
    bc() {
        if ! command -v bc > /dev/null 2>&1; then
            echo "Error: missing bc."
            exit 1
        fi
        if [ $# -eq 0 ]; then
            echo "Welcome to bc calculator. Type \"quit\" to exit."
            command bc -q -i -l
        else
            local expression=""
            for arg in "$@"; do
                if [ -n "$expression" ]; then
                    expression="$expression $arg"
                else
                    expression="$arg"
                fi
            done

            if [ -f "$1" ] && [ $# -eq 1 ]; then
                command bc -l "$@"
            else
                echo "$expression" | command bc -l
            fi
        fi
    }

    random(){
        var=$(tr -dc A-Za-z0-9 </dev/urandom | head -c $1)
        echo -n $var | xclip -selection clipboard
    }

    localhost(){
        ${BROWSER:-firefox} localhost:$1/$2 & disown
    }

}

__tools() {
    source ~/etc/dev/__old/sh/py/py
}

__prompt
__export
__alias
__func
__tools

unset -f __prompt __export __alias __func
