# DISPLAY
## set prompt to display only the colored current directory
dir1="\[\033[37m\]\w\[\033[00m\]"
PS1="$dir1\$ "
## unbolded colored directories in "ls" command
LS_COLORS=$LS_COLORS:'di=0;94:'
export LS_COLORS

# EXPORTS
export CONF_BASH=${BASH_SOURCE%/*}
export CONF=${CONF_BASH%/*}
export CONF_VIM=$CONF/vim
export CONF_XORG=$CONF/xorg
export CONF_I3=$CONF/i3
export COMPL=$CONF/compl
export BIN=$HOME/bin
export TMP=$HOME/tmp

# PATH
export PATH=$PATH:$BIN

# ADDITIONAL FILES
source $CONF_BASH/bashra 
personals=$(find $CONF -type f -name "*.ignore")
for p in ${personals[@]}; do
    source $p
done
source $CONF_VIM/vim-ai.sh

# COMPLETION
for file in $COMPL/*; do
    source "$file"
done
